[package]
name = "elliptic-curves-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ff = { version = "0.5.0", default-features = false }
ark-ff-macros = "0.5.0"
ark-secp256k1 = "0.5.0"
ark-std = "0.5.0"
num-bigint = "0.4"
num-traits = "0.2"
